### ISSUE TITLE
checkpoint problem

### ISSUE THREAD

**Issue by yic666** [YuchenLiu98/ECCV2022-SDA-FAS#1]
When I run test_SDAFAS.py in O_M_I_to_C,I encountered an error.
RuntimeError: Error(s) in loading state_dict for VisionTransformer:
	size mismatch for pos_embed: copying a param with shape torch.Size([1, 257, 384]) from checkpoint, the shape in current model is torch.Size([1, 197, 384]).

**Comment by YuchenLiu98** [comment]
For vision_transformer.py in timm, change the image_size from default 224 to 256.

**Comment by yic666** [comment]
Thanks
