### ISSUE TITLE
Can you please share the model of O&M&I to C	again?

### ISSUE THREAD

**Issue by fbiying87** [YuchenLiu98/ECCV2022-SDA-FAS#4]
Could you please update the baidu Link of your models again? The current link is not working anymore. I would really like to test some results on the test datasets. 

Thanks a lot! And I wish you a nice christmas holiday! 

Best regards,

**Comment by YuchenLiu98** [comment]
Thanks for your questions.
O&M&I to C:https://pan.baidu.com/s/1Jv-EBa7X_MUGQN2MMe674g 
access code is sdaf
