### ISSUE TITLE
可以提供一下args中的模型吗？

### ISSUE THREAD

**Issue by chenruolin2019** [YuchenLiu98/ECCV2022-SDA-FAS#7]
比如：--source_model_transformer --source_model_embedder_classifier --dataset_source_pseudo_path --dataset_path --dataset_source_pseudo_path  --dataset_target_pseudo_path 这种

**Comment by YuchenLiu98** [comment]
Please generate pseudo label yourself and put the according path in args.
Download the checkpoint and attach the path for transformer and classifier.
