### ISSUE TITLE
Models are no longer available

### ISSUE THREAD

**Issue by ahernandez900** [YuchenLiu98/ECCV2022-SDA-FAS#8]
Hello. Would it be possible to upload the pretrained models again? The page to which the links redirect to is no longer available. Many thanks.

**Comment by YuchenLiu98** [comment]
OCI to M: https://pan.baidu.com/s/1rc3qnOqZKf56jrHNQApLOA
OMI to C: https://pan.baidu.com/s/1bUQMS5V4ID4hItAfVMCRSA
OCM to I: https://pan.baidu.com/s/1UxIkzK6cAw3Q_aykRc2Z8Q
ICM to O: https://pan.baidu.com/s/13Rjm4RlR2U8gFao6uHZ4Ew
access code: sdaf
